### ISSUE TITLE
red 平台无法发送推文列表？

### ISSUE THREAD

**Issue by eric2788** [Yamamoto-2/koishi-plugin-nitter-rss#1]
沙盒和discord都可以
没有错误日志，单纯没有反应

**Comment by eric2788** [comment]
错误可能是这个
![image](https://github.com/Yamamoto-2/koishi-plugin-nitter-rss/assets/6276840/1e660e5d-e29e-42e0-bfb0-64cad8c25dfc)

但我已经有启用 puppeteer 了

**Comment by Yamamoto-2** [comment]
请你提到你发现这个问题具体哪个插件版本。而且推文列表在qqnt（red协议）发不出来是大概率事件，不仅推文列表发不出来，有时候连推文的翻译或者原文都会发不出来，因为文本太多被风控。我已经在新版本给 "获取推文" 和 订阅转发 添加了将所有文本压制为图片的方案来避免文本过多触发风控，之后我会考虑让 "推文列表" 也支持这个功能。但是推文列表功能主要目的为获取连接，不知道这样做会不会让这个功能失去本身的用途。

**Comment by eric2788** [comment]
nitter-rss 是0.0.7
adapter-red 是最新版本

正常是风控的话不应该在日志里面显示被风控么，但目前是完全没有反应

目前chronocat失效无法索取二维码了，所以现在也没办法测试
