### ISSUE TITLE
当前所有网络请求无法继承全局代理

### ISSUE THREAD

**Issue by Container-Zero** [Yamamoto-2/koishi-plugin-nitter-rss#2]
https://nitter.cz/ 需要科学才能正常访问。
但目前插件内部所有网络请求都是单独用`axios`包来完成，因此无法继承Koishi中的全局代理设置项，导致墙内目前无法正常使用。
可以使用`ctx.http.axios`来替代插件内`axios_1.default.get`之类的请求，这样就可以对接上Koishi的全局代理，希望修复一下这类问题。(或者添加一个让用户自行设置镜像站点的设置选项)
另外想请问下，使用clash的话，有什么办法可以强制所有koishi请求走clash代理，而不需要单独设置吗？

**Comment by Yamamoto-2** [comment]
https://github.com/Yamamoto-2/koishi-plugin-nitter-rss/commit/93b8df05af99e65d7d45c7ba9f9742443c10ba13
